# Generated by Django 4.0.5 on 2022-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_alter_review_user_id_delete_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reviews',
            new_name='users_review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='books_review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='the_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reviews',
            new_name='his_reviews',
        ),
        migrations.RemoveField(
            model_name='library',
            name='available_books',
        ),
        migrations.AddField(
            model_name='library',
            name='available_books',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
