# Generated by Django 4.0.5 on 2022-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_reviews_book_users_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='collection',
        ),
        migrations.AddField(
            model_name='author',
            name='collection',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
